baseurl = "https://nyl-auster.github.io/hugo-prose"
languageCode = "fr"
title = "Équité de temps de parole"
theme = "equiteparole"

#copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/mgjohansen\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"

#disqusShortname = "shortname"
googleAnalytics = "UA-93181041-1"

# github pages can be created from master/docs
publishDir = "docs"

[taxonomies]
tag = "tags"
#category = "categories"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Morten G. Johansen"
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/equite-parole/equite-parole.github.io"
fa_icon = "fa-github"

[[params.social]]
url = "https://www.facebook.com/equitetempsdeparole/"
fa_icon = "fa-facebook"

[[params.social]]
url = "https://twitter.com/equiteparole"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

# les autres liens sont définies depuis les front-matter des content/pages elles même
[[menu.main]]
    name = "Accueil"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "accueil"
    url = "/"