# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Equité temps de parole"
license = "MIT"
licenselink = "https://github.com/mgjohansen/hucore/blob/master/LICENSE.md"
description = "Theme du site équité temps de parole"
min_version = 0.16

[author]
  name = "Yann"
  homepage = "https://github.com/nyl_auster"
